### ISSUE TITLE
Still working for you?

### ISSUE THREAD

**Issue by rastarr** [affinate/reddit-account-creator#2] opened 2024-03-29 04:15 UTC
Just wondering if this is still working?

I get the following errors. Can you help?

```❯ python src/main.py 
/home/martin/devel/reddit-account-creator/.venv/lib/python3.8/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "src/main.py", line 82, in <module>
    reddit_email_input = wait_for_element(reddit_driver, By.ID, "regEmail")
  File "/home/martin/devel/reddit-account-creator/src/utils.py", line 54, in wait_for_element
    return WebDriverWait(webdriver, custom_timeout).until(
  File "/home/martin/devel/reddit-account-creator/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5619e4420993 <unknown>
#1 0x5619e411b136 <unknown>
#2 0x5619e4165d48 <unknown>
#3 0x5619e4165e01 <unknown>
#4 0x5619e41a8e44 <unknown>
#5 0x5619e4187cfd <unknown>
#6 0x5619e41a6319 <unknown>
#7 0x5619e4187a73 <unknown>
#8 0x5619e4158c93 <unknown>
#9 0x5619e415965e <unknown>
#10 0x5619e43e508b <unknown>
#11 0x5619e43e9005 <unknown>
#12 0x5619e43d3491 <unknown>
#13 0x5619e43e9b92 <unknown>
#14 0x5619e43b89ef <unknown>
#15 0x5619e440fdf8 <unknown>
#16 0x5619e440ffcb <unknown>
#17 0x5619e441fae4 <unknown>
#18 0x7f6b07d03383 start_thread```

**Comment by affinate** [comment] 2024-03-31 06:42
Looks like reddit has changed their layout making the program useless for now. Will try to fix it

**Comment by affinate** [comment] 2024-03-31 11:47
Should be fixed with c88e414

**Comment by rastarr** [comment] 2024-04-01 03:55
Thanks so much for taking a look at this.
Using python 3.10 and build the virtual environment, building open-whisper failed with wheel.
I changed to python 3.9 and the virtual environment built fine so maybe there's something wrong with 3.10.

Further, under python 3.9, I get the following error - 

```
❯ python src/main.py
Traceback (most recent call last):
  File "/home/martin/devel/reddit-account-creator/src/main.py", line 8, in <module>
    from customization import (
  File "/home/martin/devel/reddit-account-creator/src/customization.py", line 3, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
```

**Comment by affinate** [comment] 2024-04-01 13:19
Have you correctly installed the requirements in `requirements.txt`?

**Comment by rastarr** [comment] 2024-04-01 23:50
My apologies. I forgot to re-run requirements when I switched/tested to python 3.9. I'm stupid 

```
reddit-account-creator on  main [!⇡] via 🐍 v3.9.1 (.venv) via ❄️  impure (nix-shell)  took 2s 
❯ python src/main.py
INFO:root:Starting
Traceback (most recent call last):
  File "/home/martin/devel/reddit-account-creator/src/main.py", line 259, in <module>
    main()
  File "/home/martin/devel/reddit-account-creator/src/main.py", line 181, in main
    mail_driver = get_webdriver(config_webdriver)
  File "/home/martin/devel/reddit-account-creator/src/main.py", line 46, in get_webdriver
    op.set_preference(f'--user-agent="{generate_user_agent()}"')
AttributeError: 'Options' object has no attribute 'set_preference'
```

**Comment by affinate** [comment] 2024-04-03 03:53
Oh, that was a stupid error of mine not testing with chrome. Should be fixed with 3a28960

**Comment by 0xtbug** [comment] 2024-04-06 04:27
Hi @affinate, i tried your program and got an error like this

```
Traceback (most recent call last):
  File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
    main()
  File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
    solve_captcha(reddit_driver, config_audio_language)
  File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
    solver.solve()
  File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
    self._solve_audio_challenge()
  File "D:\tools\reddit-account-creator\src\solver.py", line 160, in _solve_audio_challenge
    audio = whisper.load_audio(audio_challenge_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\whisper\audio.py", line 48, in load_audio
    .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
The program automatically closes after downloading the google audio challange captcha

**Comment by affinate** [comment] 2024-04-06 09:10
> Hi @affinate, i tried your program and got an error like this
> 
> ```
> Traceback (most recent call last):
>   File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
>     main()
>   File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
>     solve_captcha(reddit_driver, config_audio_language)
>   File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
>     solver.solve()
>   File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
>     self._solve_audio_challenge()
>   File "D:\tools\reddit-account-creator\src\solver.py", line 160, in _solve_audio_challenge
>     audio = whisper.load_audio(audio_challenge_file)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\whisper\audio.py", line 48, in load_audio
>     .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 313, in run
>     process = run_async(
>               ^^^^^^^^^^
>   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 284, in run_async
>     return subprocess.Popen(
>            ^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```
> 
> The program automatically closes after downloading the google audio challange captcha

You need to download [ffmpeg](https://ffmpeg.org/download.html) and put it in your PATH system variables

**Comment by 0xtbug** [comment] 2024-04-06 11:53
> > Hi @affinate, i tried your program and got an error like this
> > ```
> > Traceback (most recent call last):
> >   File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
> >     main()
> >   File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
> >     solve_captcha(reddit_driver, config_audio_language)
> >   File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
> >     solver.solve()
> >   File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
> >     self._solve_audio_challenge()
> >   File "D:\tools\reddit-account-creator\src\solver.py", line 160, in _solve_audio_challenge
> >     audio = whisper.load_audio(audio_challenge_file)
> >             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\whisper\audio.py", line 48, in load_audio
> >     .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
> >      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 313, in run
> >     process = run_async(
> >               ^^^^^^^^^^
> >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 284, in run_async
> >     return subprocess.Popen(
> >            ^^^^^^^^^^^^^^^^^
> >   File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
> >     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> >                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > FileNotFoundError: [WinError 2] The system cannot find the file specified
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The program automatically closes after downloading the google audio challange captcha
> 
> You need to download [ffmpeg](https://ffmpeg.org/download.html) and put it in your PATH system variables

Thank you, the problem is solved, but, there are other errors :
```
INFO:root:Starting
INFO:root:Inputting password
INFO:root:Solving captcha
Traceback (most recent call last):
  File "D:\tools\reddit-account-creator\src\solver.py", line 109, in get_download_link
    download_link: WebElement = wait_for_element(
                                ^^^^^^^^^^^^^^^^^
  File "D:\tools\reddit-account-creator\src\utils.py", line 53, in wait_for_element
    return WebDriverWait(webdriver, custom_timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:510:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
    main()
  File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
    solve_captcha(reddit_driver, config_audio_language)
  File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
    solver.solve()
  File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
    self._solve_audio_challenge()
  File "D:\tools\reddit-account-creator\src\solver.py", line 146, in _solve_audio_challenge
    audio_link = get_download_link()
                 ^^^^^^^^^^^^^^^^^^^
  File "D:\tools\reddit-account-creator\src\solver.py", line 126, in get_download_link
    raise UnkownGoogleError("Unkown error. Try again")
solver.UnkownGoogleError: Unkown error. Try again

```

**Comment by 0xtbug** [comment] 2024-04-06 12:22
> > > Hi @affinate, i tried your program and got an error like this
> > > ```
> > > Traceback (most recent call last):
> > >   File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
> > >     main()
> > >   File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
> > >     solve_captcha(reddit_driver, config_audio_language)
> > >   File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
> > >     solver.solve()
> > >   File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
> > >     self._solve_audio_challenge()
> > >   File "D:\tools\reddit-account-creator\src\solver.py", line 160, in _solve_audio_challenge
> > >     audio = whisper.load_audio(audio_challenge_file)
> > >             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\whisper\audio.py", line 48, in load_audio
> > >     .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
> > >      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 313, in run
> > >     process = run_async(
> > >               ^^^^^^^^^^
> > >   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 284, in run_async
> > >     return subprocess.Popen(
> > >            ^^^^^^^^^^^^^^^^^
> > >   File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
> > >     self._execute_child(args, executable, preexec_fn, close_fds,
> > >   File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
> > >     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > >                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > FileNotFoundError: [WinError 2] The system cannot find the file specified
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The program automatically closes after downloading the google audio challange captcha
> > 
> > 
> > You need to download [ffmpeg](https://ffmpeg.org/download.html) and put it in your PATH system variables
> 
> Thank you, the problem is solved, but, there are other errors :
> 
> ```
> INFO:root:Starting
> INFO:root:Inputting password
> INFO:root:Solving captcha
> Traceback (most recent call last):
>   File "D:\tools\reddit-account-creator\src\solver.py", line 109, in get_download_link
>     download_link: WebElement = wait_for_element(
>                                 ^^^^^^^^^^^^^^^^^
>   File "D:\tools\reddit-account-creator\src\utils.py", line 53, in wait_for_element
>     return WebDriverWait(webdriver, custom_timeout).until(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\tubag\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\support\wait.py", line 95, in until
>     raise TimeoutException(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message:
> Stacktrace:
> RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
> WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5
> NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:510:5
> dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\tools\reddit-account-creator\src\main.py", line 258, in <module>
>     main()
>   File "D:\tools\reddit-account-creator\src\main.py", line 228, in main
>     solve_captcha(reddit_driver, config_audio_language)
>   File "D:\tools\reddit-account-creator\src\main.py", line 66, in solve_captcha
>     solver.solve()
>   File "D:\tools\reddit-account-creator\src\solver.py", line 63, in solve
>     self._solve_audio_challenge()
>   File "D:\tools\reddit-account-creator\src\solver.py", line 146, in _solve_audio_challenge
>     audio_link = get_download_link()
>                  ^^^^^^^^^^^^^^^^^^^
>   File "D:\tools\reddit-account-creator\src\solver.py", line 126, in get_download_link
>     raise UnkownGoogleError("Unkown error. Try again")
> solver.UnkownGoogleError: Unkown error. Try again
> ```

Lol solved, I just changed the audio language in utils.py

**Comment by vinskasenda** [comment] 2024-04-07 21:54
work ?

**Comment by affinate** [comment] 2024-04-10 11:22
@vinskasenda Everything should work

**Comment by affinate** [comment] 2024-04-10 11:22
@rastarr Can I close this issue or do you have other problems with the program?

**Comment by AmmarNaufalP** [comment] 2024-04-12 08:50
@affinate can we automate change IPs?

**Comment by affinate** [comment] 2024-04-12 11:07
> @affinate can we automate change IPs?

There are VPN CLI tools which you can use to automate the IP change

**Comment by AmmarNaufalP** [comment] 2024-04-12 15:54
There's a way to click "Continue" Button without pressing key Enter? Because it's doesn't work with 2captcha solver

**Comment by affinate** [comment] 2024-04-13 23:35
> @affinate There's a way to click "Continue" Button without pressing key Enter? Because it's doesn't work with 2captcha solver

Weird, pressing enter should work. 
I currently don't have time to look into that. Can you open a separate issue with the reproduction steps so someone else can help you?

**Closed by affinate** 2024-04-13 23:35 UTC
